//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public int group_member_id { get; set; }
        public Nullable<int> member_id { get; set; }
        public Nullable<int> group_id { get; set; }
    
        public virtual MyGroup MyGroup { get; set; }
        public virtual Member Member { get; set; }
    }
}
