//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyGroup
    {
        public MyGroup()
        {
            this.GroupMembers = new HashSet<GroupMember>();
        }
    
        public int group_id { get; set; }
        public string group_name { get; set; }
    
        public virtual ICollection<GroupMember> GroupMembers { get; set; }
    }
}
